config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('distribution/', include('distribution.urls', namespace='distribution')),
    path('users/', include('users.urls', namespace='users')),
]

distribution/urls.py
from django.urls import path

from distribution.views import DistributionListView, RecipientListView, MessageListView, ContactTemplateView, \
    MessageCreateView, RecipientCreateView, DistributionCreateView, DistributionUpdateView, MessageUpdateView, \
    RecipientUpdateView, DistributionDeleteView, MessageDeleteView, RecipientDeleteView, send_mailing, count_main, \
    stop_mailing, ReportsListView, UserListView, block_user

app_name = 'distribution'

urlpatterns = [
    path('', DistributionListView.as_view(), name='distributions'),
    path('messages/', MessageListView.as_view(), name='messages'),
    path('recipients/', RecipientListView.as_view(), name='recipients'),
    path('contacts/', ContactTemplateView.as_view(), name='contacts'),
    path('message/create', MessageCreateView.as_view(), name='mes_create'),
    path('recipient/create', RecipientCreateView.as_view(), name='rec_create'),
    path('distribution/create', DistributionCreateView.as_view(), name='dis_create'),
    path('distribution/update/<int:pk>', DistributionUpdateView.as_view(), name='dis_update'),
    path('recipient/update/<int:pk>', RecipientUpdateView.as_view(), name='rec_update'),
    path('message/update/<int:pk>', MessageUpdateView.as_view(), name='mes_update'),
    path('distribution/delete/<int:pk>', DistributionDeleteView.as_view(), name='dis_delete'),
    path('recipient/delete/<int:pk>', RecipientDeleteView.as_view(), name='rec_delete'),
    path('message/delete/<int:pk>', MessageDeleteView.as_view(), name='mes_delete'),
    path('distribution/send_distribution/<int:pk>', send_mailing, name='send_dis'),
    path('distribution/send_data/', count_main, name='count'),
    path('distribution/stop/<int:pk>', stop_mailing, name='stop'),
    path('reports/', ReportsListView.as_view(), name='reports'),
    path('user_list/', UserListView.as_view(), name='users_list'),
    path('block/<int:pk>', block_user, name='block'),
]

users/urls.py
from django.urls import path

from users.views import RegisterView, profile_info, UserUpdatePasswordView
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'users'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(next_page='distribution:distributions'), name='logout'),
    path('profile/<int:pk>', profile_info, name='profile'),
    path('password/<int:pk>', UserUpdatePasswordView.as_view(), name='change_pass'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class CustomUser(AbstractUser):
    phone_number = models.CharField(max_length=15, blank=True, null=True)
    avatar = models.ImageField()
    country = models.CharField(max_length=30)
    email = models.EmailField(unique=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username',]

users/forms.py
from django.contrib.auth.forms import UserCreationForm

from users.models import CustomUser


# Create your views here.

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = ('username', 'email', 'password1', 'password2',)

    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({
            'class':'form-control',
            'placeholder':'Введите логин'
        })
        self.fields['email'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Введите почту'
        })
        self.fields['password1'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Введите пароль'
        })
        self.fields['password2'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Подтвердите пароль'
        })


class CustomUserUpdatePasswordForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = ('password1', 'password2',)

    def __init__(self, *args, **kwargs):
        super(CustomUserUpdatePasswordForm, self).__init__(*args, **kwargs)
        self.fields['password1'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Введите пароль'
        })
        self.fields['password2'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Подтвердите пароль'
        })

users/views.py
from msilib.schema import ListView

from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import CreateView, UpdateView
from django.core.mail import send_mail

from users.forms import CustomUserCreationForm, CustomUserUpdatePasswordForm
from users.models import CustomUser


# Create your views here.
class RegisterView(CreateView):
    template_name = 'register.html'
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('distribution:distribution')


    def form_valid(self, form):
        user = form.save()
        self.send_welcome_massage(user.email)
        return super().form_valid(form)


    def send_welcome_massage(self, user_email):
        subject = 'Добро пожаловать на наш сайт!'
        message = 'Регистрация прошла успешно!'
        from_email = 'sergeibordeichuk@yandex.ru'
        recipient_list = [user_email,]
        send_mail(subject, message, from_email, recipient_list)


def profile_info(request, pk):
    user = CustomUser.objects.get(pk=pk)
    context = {'username': user.username,
               'email': user.email,
               'phone': user.phone_number,
               'fullname': f'{user.first_name} {user.last_name}',
               'country': user.country,
               'pk': user.pk,
               }
    template_name = 'profile.html'
    return render(request, template_name, context)


class UserUpdatePasswordView(UpdateView, LoginRequiredMixin):
    model = CustomUser
    form_class = CustomUserUpdatePasswordForm
    template_name = 'change_password.html'
    success_url = reverse_lazy('distribution:distributions')

users/templates/base_user.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">SkyProject</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="{% url 'distribution:recipients' %}">Получатели</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'distribution:messages' %}">Сообщения</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'distribution:distributions' %}">Рассылки</a>
        {% if user.is_authenticated %}
            <a class="p-2 btn btn-outline-primary" href="{% url 'distribution:reports' %}">Отчеты</a>
        {% endif %}
        <a class="p-2 btn btn-outline-primary" href="{% url 'distribution:contacts' %}">Контакты</a>
        {% if user.is_authenticated %}
        <form method="post" action="{% url 'users:logout' %}" style="display: inline">
            {% csrf_token %}
            <button type="submit" class="p-2 btn btn-outline-primary">Выйти</button>
        </form>
        {% else %}
        <a class="p-2 btn btn-outline-primary" href="{% url 'users:login' %}">Войти</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'users:register' %}">Регистрация</a>
        {% endif %}
    </nav>
</div>



<div class="container">
    {% block content %}
    {% endblock %}
    <footer class="pt-4 my-md-5 pt-md-5 border-top">
    {% include 'includes/inc_supp.html' %}
    </footer>
</div>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

users/templates/change_password.html
{% extends 'base_user.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Изменить пароль</h1>
</div>
    <form method="post" action="" class="form-floating">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Изменить</button>
        <a href="{% url 'distribution:distributions' %}" class="btn btn-lg btn-block btn-outline-secondary">Назад</a>
    </form>
{% endblock %}

users/templates/login.html
{% extends 'base_user.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Login</h1>
</div>
    <form method="post" action="" class="form-floating">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Войти</button>
        <a href="{% url 'distribution:distributions' %}" class="btn btn-lg btn-block btn-outline-secondary">Назад</a>
    </form>
{% endblock %}

users/templates/profile.html
{% extends 'base_user.html' %}
{% block content %}
<div class="row text-center">
        <div class="col-3">
            <div class="card mb-4" style="width: 18rem;">
                  <div class="card-body">
                      <h5 class="card-title">{{ username }}</h5>
                      <p class="card-text">{{ email }}</p>
                      <p class="card-text">{{ fullname }}</p>
                      <p class="card-text">{{ country }}</p>
                      <p class="card-text">{{ phone }}</p>
                      <a href="{% url 'users:change_pass' pk %}" class="btn btn-lg btn-block btn-outline-danger">Изменить пароль</a>
                      <a href="{% url 'distribution:distributions' %}" class="btn btn-lg btn-block btn-outline-secondary">Назад</a>
                  </div>
            </div>
        </div>
</div>
{% endblock %}

users/templates/register.html
{% extends 'base_user.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Регистрация</h1>
</div>
    <form method="post" action="" class="form-floating">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Зарегистрироваться</button>
        <a href="{% url 'distribution:distributions' %}" class="btn btn-lg btn-block btn-outline-secondary">Назад</a>
    </form>
{% endblock %}