config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('distribution/', include('distribution.urls', namespace='distribution')),
    path('users/', include('users.urls', namespace='users')),
]

distribution/urls.py
from django.urls import path

from distribution.views import DistributionListView, RecipientListView, MessageListView, ContactTemplateView, \
    MessageCreateView, RecipientCreateView, DistributionCreateView, DistributionUpdateView, MessageUpdateView, \
    RecipientUpdateView, DistributionDeleteView, MessageDeleteView, RecipientDeleteView, send_mailing, count_main, \
    stop_mailing, ReportsListView, UserListView, block_user

app_name = 'distribution'

urlpatterns = [
    path('', DistributionListView.as_view(), name='distributions'),
    path('messages/', MessageListView.as_view(), name='messages'),
    path('recipients/', RecipientListView.as_view(), name='recipients'),
    path('contacts/', ContactTemplateView.as_view(), name='contacts'),
    path('message/create', MessageCreateView.as_view(), name='mes_create'),
    path('recipient/create', RecipientCreateView.as_view(), name='rec_create'),
    path('distribution/create', DistributionCreateView.as_view(), name='dis_create'),
    path('distribution/update/<int:pk>', DistributionUpdateView.as_view(), name='dis_update'),
    path('recipient/update/<int:pk>', RecipientUpdateView.as_view(), name='rec_update'),
    path('message/update/<int:pk>', MessageUpdateView.as_view(), name='mes_update'),
    path('distribution/delete/<int:pk>', DistributionDeleteView.as_view(), name='dis_delete'),
    path('recipient/delete/<int:pk>', RecipientDeleteView.as_view(), name='rec_delete'),
    path('message/delete/<int:pk>', MessageDeleteView.as_view(), name='mes_delete'),
    path('distribution/send_distribution/<int:pk>', send_mailing, name='send_dis'),
    path('distribution/send_data/', count_main, name='count'),
    path('distribution/stop/<int:pk>', stop_mailing, name='stop'),
    path('reports/', ReportsListView.as_view(), name='reports'),
    path('user_list/', UserListView.as_view(), name='users_list'),
    path('block/<int:pk>', block_user, name='block'),
]

users/urls.py
from django.urls import path

from users.views import RegisterView, profile_info, UserUpdatePasswordView
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'users'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(next_page='distribution:distributions'), name='logout'),
    path('profile/<int:pk>', profile_info, name='profile'),
    path('password/<int:pk>', UserUpdatePasswordView.as_view(), name='change_pass'),
]

distribution/models.py
from django.db import models

from users.models import CustomUser


# Create your models here.

class MailingRecipient(models.Model):
    email = models.EmailField(unique=True)
    full_name = models.CharField(max_length=100)
    comment = models.TextField(null=True, blank=True)

    owner = models.ForeignKey(CustomUser, verbose_name='Владелец', help_text='Укажите владельца продукта',
                              on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return f'{self.full_name} {self.email}'

    class Meta:
        verbose_name = 'получатель'
        verbose_name_plural = 'получатели'


class Message(models.Model):
    theme = models.CharField(max_length=100)
    message = models.TextField()

    owner = models.ForeignKey(CustomUser, verbose_name='Владелец', help_text='Укажите владельца продукта',
                              on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return f'{self.theme}'

    class Meta:
        verbose_name = 'сообщение'
        verbose_name_plural = 'сообщения'


class Distribution(models.Model):
    STATUS_CHOICES = (
        ('Completed', 'Завершена'),
        ('Created', 'Создана'),
        ('Launched', 'Запущена'),
    )
    first_sending = models.DateTimeField(auto_now_add=True)
    last_sending = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='Created')
    message = models.ForeignKey(Message, on_delete=models.CASCADE)
    recipients = models.ManyToManyField(MailingRecipient)

    owner = models.ForeignKey(CustomUser, verbose_name='Владелец', help_text='Укажите владельца продукта',
                              on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return f'{self.message}'

    class Meta:
        verbose_name = 'рассылка'
        verbose_name_plural = 'рассылки'
        permissions = [
            ("stop_distribution", "Can stop distribution"),
            ("start_distribution", "Can start distribution"),
            ("block_user", "Can block user"),
            ("view_user", "Can view user"),
        ]


class AttemptToSend(models.Model):
    STATUS_CHOICES = (
        ('Successfully', 'Успешно'),
        ('Not successful', 'Не успешно'),
    )
    date_attempt = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES)
    response = models.TextField()
    distribution = models.ForeignKey(Distribution, on_delete=models.CASCADE)


    class Meta:
        verbose_name = 'отчет'
        verbose_name_plural = 'отчеты'
        permissions = [
            ("view_reports", "Can view reports"),
        ]

distribution/forms.py
from django.forms import ModelForm

from distribution.models import Message, MailingRecipient, Distribution


class MessageForm(ModelForm):
    class Meta:
        model = Message
        fields = ['theme', 'message',]

    def __init__(self, *args, **kwargs):
        super(MessageForm, self).__init__(*args, **kwargs)
        self.fields['theme'].widget.attrs.update({
            'class':'form-control',
            'placeholder':'Введите тему сообщения',
        })
        self.fields['message'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Введите сообщение',
        })


class RecipientForm(ModelForm):
    class Meta:
        model = MailingRecipient
        fields = ['email', 'full_name', 'comment',]

    def __init__(self, *args, **kwargs):
        super(RecipientForm, self).__init__(*args, **kwargs)
        self.fields['email'].widget.attrs.update({
            'class':'form-control',
            'placeholder':'Введите почту',
        })
        self.fields['full_name'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Введите полное имя',
        })
        self.fields['comment'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Введите комментарий',
        })


class DistributionForm(ModelForm):
    class Meta:
        model = Distribution
        fields = ['message', 'recipients',]

    def __init__(self, *args, **kwargs):
        super(DistributionForm, self).__init__(*args, **kwargs)
        self.fields['message'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Введите сообщение',
        })
        self.fields['recipients'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Введите получателя',
        })

distribution/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.forms import BaseForm
from django.http import HttpResponseForbidden, HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse_lazy

from distribution.celery import app
from distribution.models import Distribution, Message, MailingRecipient, AttemptToSend
from distribution.forms import DistributionForm, MessageForm, RecipientForm

from celery import shared_task
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic import DetailView, ListView, TemplateView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from django.core.cache import cache
from django.views.decorators.cache import cache_page

from django.core.mail import send_mail
from django.conf import settings

from users.models import CustomUser


class ContactTemplateView(TemplateView):
    template_name = 'contacts.html'


class MessageListView(ListView):
    model = Message
    template_name = 'message_list.html'
    context_object_name = 'messages'


class RecipientListView(ListView):
    model = MailingRecipient
    template_name = 'recipient_list.html'
    context_object_name = 'recipients'


class DistributionListView(ListView):
    model = Distribution
    template_name = 'distribution_list.html'
    context_object_name = 'distributions'


class DistributionCreateView(CreateView, LoginRequiredMixin):
    model = Distribution
    form_class = DistributionForm
    template_name = 'distribution_form.html'
    success_url = reverse_lazy('distribution:distributions')

    def form_valid(self, form):
        distribution = form.save()
        user = self.request.user
        distribution.owner = user
        distribution.save()
        return super().form_valid(form)


class MessageCreateView(CreateView, LoginRequiredMixin):
    model = Message
    form_class = MessageForm
    template_name = 'message_form.html'
    success_url = reverse_lazy('distribution:messages')

    def form_valid(self, form):
        distribution = form.save()
        user = self.request.user
        distribution.owner = user
        distribution.save()
        return super().form_valid(form)


class RecipientCreateView(CreateView, LoginRequiredMixin):
    model = MailingRecipient
    form_class = RecipientForm
    template_name = 'recipient_form.html'
    success_url = reverse_lazy('distribution:recipients')

    def form_valid(self, form):
        recipient = form.save()
        user = self.request.user
        recipient.owner = user
        recipient.save()
        return super().form_valid(form)


class DistributionUpdateView(UpdateView, LoginRequiredMixin):
    model = Distribution
    form_class = DistributionForm
    template_name = 'distribution_form.html'
    success_url = reverse_lazy('distribution:distributions')


class MessageUpdateView(UpdateView, LoginRequiredMixin):
    model = Message
    form_class = MessageForm
    template_name = 'message_form.html'
    success_url = reverse_lazy('distribution:messages')


class RecipientUpdateView(UpdateView, LoginRequiredMixin):
    model = MailingRecipient
    form_class = RecipientForm
    template_name = 'recipient_form.html'
    success_url = reverse_lazy('distribution:recipients')


class DistributionDeleteView(DeleteView, LoginRequiredMixin):
    model = Distribution
    template_name = 'confirm_delete.html'
    success_url = reverse_lazy('distribution:distribution')


class MessageDeleteView(DeleteView, LoginRequiredMixin):
    model = Message
    template_name = 'confirm_delete.html'
    success_url = reverse_lazy('distribution:messages')


class RecipientDeleteView(DeleteView, LoginRequiredMixin):
    model = MailingRecipient
    template_name = 'confirm_delete.html'
    success_url = reverse_lazy('distribution:recipients')


@app.task()
def send_mailing(request, pk):
    mailing = Distribution.objects.get(pk=pk)
    recipients = mailing.recipients.all()
    mailing.status = 'Launched'
    mailing.save()
    if mailing.status != 'Launched':
        return redirect('distribution:distributions')
    else:
        for recipient in recipients:
            try:
                send_mail(
                    subject=mailing.message.theme,
                    message=mailing.message.message,
                    from_email=settings.EMAIL_HOST_USER,
                    recipient_list=[recipient.email],
                    fail_silently=False,
                )
                AttemptToSend.objects.create(status='Successfully', response='', distribution=mailing)
            except Exception as e:
                AttemptToSend.objects.create(status='Not successful', response=str(e), distribution=mailing)
        return redirect('distribution:distributions')

def stop_mailing(request, pk):
    mailing = Distribution.objects.get(pk=pk)
    mailing.status = 'Completed'
    mailing.save()
    return redirect('distribution:distributions')


def count_main(request):
    recipients = []
    count_active_dis = 0
    for dist in Distribution.objects.get():
        if dist.status == 'Launched':
            count_active_dis += 1
        for recipient in dist.recipients:
            recipients.append(recipient)
    count_recipients = len(set(recipients))
    context= {'count_recipients': count_recipients, 'count_active_dist':count_active_dis}
    return render(request, 'distribution_list.html', context=context)

class ReportsListView(ListView, LoginRequiredMixin):
    model = AttemptToSend
    template_name = 'reports.html'
    context_object_name = 'reports'


class UserListView(ListView):
    model = CustomUser
    template_name = 'users_list.html'
    context_object_name = 'users'


def block_user(request, pk):
    user = CustomUser.objects.get(pk=pk)
    user.is_active = False
    user.save()
    return redirect('distribution:distributions')

distribution/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>SkySend</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">SkyProject</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="{% url 'distribution:recipients' %}">Получатели</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'distribution:messages' %}">Сообщения</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'distribution:distributions' %}">Рассылки</a>
        {% if user.is_authenticated %}
            <a class="p-2 btn btn-outline-primary" href="{% url 'distribution:reports' %}">Отчеты</a>
        {% endif %}
        {% if user.is_authenticated and 'distribution.view_users' in perms %}
            <a class="p-2 btn btn-outline-primary" href="{% url 'distribution:users_list' %}">Пользователи</a>
        {% endif %}
        <a class="p-2 btn btn-outline-primary" href="{% url 'distribution:contacts' %}">Контакты</a>
        {% if user.is_authenticated %}
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:profile' user.pk %}">Профиль</a>
            <form method="post" action="{% url 'users:logout' %}" style="display: inline">
                {% csrf_token %}
                <button type="submit" class="p-2 btn btn-outline-primary">Выйти</button>
            </form>
        {% else %}
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:login' %}">Войти</a>
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:register' %}">Регистрация</a>
        {% endif %}
    </nav>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">SkySend</h1>
    <p class="lead">Skystore - это отличный вариант хранения ваших плагинов и примеров кода, который вы бы хотели
        продать</p>
</div>

<div class="container">
    {% block content %}
    {% endblock %}
    <footer class="pt-4 my-md-5 pt-md-5 border-top">
    {% include 'includes/inc_supp.html' %}
    </footer>
</div>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

distribution/templates/confirm_delete.html
{% extends 'base.html' %}
{% block content %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h2 class="display-4">Вы точно хотите удалить?</h2>
        <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-lg btn-block btn-outline-danger">Удалить</button>
                        <a href="{% url 'distribution:distributions' %}" class="btn btn-lg btn-block btn-outline-secondary">Отмена</a>
                    </form>
    </div>
{% endblock %}

distribution/templates/contacts.html
{% extends 'base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>Russian Federation</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Moscow</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea  name="message" class="form-control" id="message" placeholder="Контактный телефон" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

distribution/templates/distribution_form.html
{% extends 'base.html' %}
{% block content %}
    <form method="post" action="" class="form-floating">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
        <a href="{% url 'distribution:distributions' %}" class="btn btn-lg btn-block btn-outline-secondary">Назад</a>
    </form>
{% endblock %}

distribution/templates/distribution_list.html
{% extends 'base.html' %}

{% block content %}

{% if user.is_authenticated %}
    <p class="lead">Количество активных рассылок: {{ count_active_dist }}</p>
    <p class="lead">Количество рассылок: {{ distributions.count }}</p>
    <p class="lead">Количество уникальных получателей: {{ count_recipients }}</p>
    <a href="{% url 'distribution:dis_create' %}" class="btn btn-lg btn-block btn-outline-primary mb-4">Добавить Рассылку</a>
{% endif %}
<div class="row text-center">
    {% for distribution in distributions %}
        <div class="col-3">
            <div class="card mb-4" style="width: 18rem;">
                  <div class="card-body">
                      <h5 class="card-title">{{ distribution.message }}</h5>
                      {% for recipients in distribution.recipients.all %}
                          <p class="card-text">{{ recipients.email }}</p>
                      {% endfor %}
                      {% if user.is_authenticated %}
                          <a href="#" class="btn btn-primary mb-1">Посмотреть</a>
                          {% if user == distribution.owner or 'distribution.update_distribution' %}
                              <a href="{% url 'distribution:dis_update' distribution.pk %}" class="btn btn-secondary mb-1">Редактировать</a>
                          {% endif %}
                          {% if user == distribution.owner or 'distribution.delete_distribution' %}
                              <a href="{% url 'distribution:dis_delete' distribution.pk %}" class="btn btn-danger mb-1">Удалить</a>
                          {% endif %}
                          {% if distribution.status != 'Launched' %}
                            {% if user == distribution.owner or 'distribution.start_distribution' %}
                              <a href="{% url 'distribution:send_dis' distribution.pk %}" class="btn btn-primary mb-1">Начать рассылку</a>
                            {% endif %}
                          {% endif %}
                          {% if distribution.status == 'Launched' %}
                            {% if user == distribution.owner or 'distribution.stop_distribution' %}
                              <a href="{% url 'distribution:stop' distribution.pk %}" class="btn btn-primary mb-1">Остановить рассылку</a>
                            {% endif %}
                          {% endif %}
                      {% endif %}
                  </div>
            </div>
        </div>
    {% endfor %}
</div>
{% endblock %}

distribution/templates/message_form.html
{% extends 'base.html' %}
{% block content %}
    <form method="post" action="" class="form-floating">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
        <a href="{% url 'distribution:messages' %}" class="btn btn-lg btn-block btn-outline-secondary">Назад</a>
    </form>
{% endblock %}

distribution/templates/message_list.html
{% extends 'base.html' %}

{% block content %}

{% if user.is_authenticated %}
    <a href="{% url 'distribution:mes_create' %}" class="btn btn-lg btn-block btn-outline-primary mb-4">Добавить Сообщение</a>
{% endif %}
<div class="row text-center">
    {% if user.is_authenticated %}
        {% for message in messages %}
            {% if user == message.owner or 'distribution.view_message' %}
                <div class="col-3">
                    <div class="card mb-4" style="width: 18rem;">
                          <div class="card-body">
                              <h5 class="card-title">{{ message.theme }}</h5>
                              <p class="card-text">{{ message.message }}</p>
                              {% if user.is_authenticated %}
                                  <a href="#" class="btn btn-primary mb-1">Посмотреть</a>
                                  {% if user == message.owner or 'distribution.update_message' %}
                                      <a href="{% url 'distribution:mes_update' message.pk %}" class="btn btn-secondary mb-1">Редактировать</a>
                                  {% endif %}
                                  {% if user == message.owner or 'distribution.delete_message' %}
                                      <a href="{% url 'distribution:mes_delete' message.pk %}" class="btn btn-danger mb-1">Удалить</a>
                                  {% endif %}
                              {% endif %}
                          </div>
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}
</div>
{% endblock %}

distribution/templates/recipient_form.html
{% extends 'base.html' %}
{% block content %}
    <form method="post" action="" class="form-floating">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
        <a href="{% url 'distribution:recipients' %}" class="btn btn-lg btn-block btn-outline-secondary">Назад</a>
    </form>
{% endblock %}

distribution/templates/recipient_list.html
{% extends 'base.html' %}

{% block content %}

{% if user.is_authenticated %}
    <a href="{% url 'distribution:rec_create' %}" class="btn btn-lg btn-block btn-outline-primary mb-4">Добавить Получателя</a>
{% endif %}
<div class="row text-center">
    {% for recipient in recipients %}
        <div class="col-3">
            <div class="card mb-4" style="width: 18rem;">
                  <div class="card-body">
                      <h5 class="card-title">{{ recipient.full_name }}</h5>
                      <p class="card-text">{{ recipient.comment }}</p>
                      {% if user.is_authenticated %}
                          <a href="#" class="btn btn-primary mb-1">Посмотреть</a>
                          {% if user == recipient.owner or 'distribution.update_recipient' %}
                              <a href="{% url 'distribution:rec_update' recipient.pk %}" class="btn btn-secondary mb-1">Редактировать</a>
                          {% endif %}
                          {% if user == recipient.owner or 'distribution.delete_recipient' %}
                              <a href="{% url 'distribution:rec_delete' recipient.pk %}" class="btn btn-danger mb-1">Удалить</a>
                          {% endif %}
                      {% endif %}
                  </div>
            </div>
        </div>
    {% endfor %}
</div>
{% endblock %}

distribution/templates/reports.html
{% extends 'base.html' %}

{% block content %}
<div class="row text-center">
    {% for report in reports %}
        <div class="col-3">
            <div class="card mb-4" style="width: 18rem;">
                  <div class="card-body">
                      <h5 class="card-title">{{ report.status }}</h5>
                      <p class="card-text">{{ report.distribution }}</p>
                      <p class="card-text">{{ report.response }}</p>
                      <p class="card-text">{{ report.date_attempt }}</p>
                  </div>
            </div>
        </div>
    {% endfor %}
</div>
{% endblock %}

distribution/templates/users_list.html
{% extends 'base_user.html' %}

{% block content %}

<div class="row text-center">
    {% for user in users %}
        <div class="col-3">
            <div class="card mb-4" style="width: 18rem;">
                  <div class="card-body">
                      <h5 class="card-title">{{ user.username }}</h5>
                      <p class="card-text">{{ user.email }}</p>
                      <p class="card-text">{{ user.country }}</p>
                      <p class="card-text">{{ user.phone_number }}</p>
                      <p class="card-text">{{ user.email }}</p>
                      <p class="card-text">{{ user.email }}</p>
                      {% if user.is_authenticated and 'distribution.block_user' %}
                          <a href="{% url 'distribution:block' user.pk %}" class="btn btn-danger mb-1">Заблокировать</a>
                      {% endif %}
                  </div>
            </div>
        </div>
    {% endfor %}
</div>
{% endblock %}